
name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test || echo "No tests specified"

      - name: Build
        run: npm run build

      - name: Validate build
        run: |
          if [ ! -d "dist" ]; then
            echo "Build failed - dist directory not found"
            exit 1
          fi

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Starting deployment at $(date)"
            cd /var/www/precision-vps
            
            # Backup current version before pull
            timestamp=$(date +"%Y%m%d-%H%M%S")
            git branch "backup-$timestamp" || echo "Failed to create backup branch, continuing anyway"
            
            # Pull latest changes
            git pull
            
            # Install dependencies
            npm ci --production
            
            # Build the application
            npm run build
            
            # Restart the application
            pm2 restart precision-app || pm2 start npm --name "precision-app" -- start
            
            # Verify deployment
            pm2 status precision-app
            
            echo "Deployment completed at $(date)"
